### ISSUE TITLE
支持把http client开放出来，让用户配置

### ISSUE THREAD

**Issue by demonwy** [aliyun/aliyun-oss-go-sdk#72]
［期望］
你好，我们需要oss client把http client开放出来，支持自定义配置。
［定位］
位置如下：
https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/conn.go#L58

**Comment by ncw** [comment]
Yes please - this is essential for rclone to work properly.  I need to be able to pass in either an http.Client or an http.Transport as an option to NewClient.

I'm willing to send a PR if you think that would be useful.

**Comment by hangzws** [comment]
I don't think this is a good suggestion, there may cause some bugs. We have provided some methods for setting the parameters of http client through the option args. Are you doing this to be compatible with rclone? Is there a better way?

**Comment by ncw** [comment]
It is normal with go http libraries to be able to pass in either `http.Client` or `http.Transport`.  For example with [google appengine](https://cloud.google.com/appengine/docs/standard/go/urlfetch/reference), they **require** that you use their `http.Transport`.

I know (because I have used their APIs in rclone) that the official go SDKs for: Amazon s3, Google cloud storage, Microsoft azure blob, Google drive and QingStor all allow you to pass in a Transport or a Client.

Not being able to pass in `http.Client` or `http.Transport` limits the use of this library unfortunately :-(

> We have provided some methods for setting the parameters of http client through the option args.

But no way of overriding the http.Client or http.Transport as far as I can see.

**Comment by ncw** [comment]
Would someone like to review my PR #76 implementing this?

**Comment by hangzws** [comment]
Ok, we will check it.

**Comment by ncw** [comment]
It looks like this was fixed in https://github.com/aliyun/aliyun-oss-go-sdk/commit/34e27f16 - thank you
