### ISSUE TITLE
signURL 不能处理object key中包含/路径分隔符

### ISSUE THREAD

**Issue by jiyeyuran** [aliyun/aliyun-oss-go-sdk#82]
如果object key中包含路径分隔符/，signURL会将/转换为%252F，导致返回的url无法使用。

**Comment by cssivision** [comment]
you should use url.QueryUnescape method

**Comment by jiyeyuran** [comment]
感觉没必要在SignURL里面对key做url.QueryEscape吧，返回以后还是要url.QueryUnescape

**Comment by koolay** [comment]
可否给个例子? 这是常见问题

**Comment by koolay** [comment]
```
      	ur, err := url.Parse(rawURL)
	if err != nil {
		return err
	}
	epath, err := url.PathUnescape(ur.Path)
	if err != nil {
		return err
	}

	return bucket.SignURL(strings.TrimLeft(epath, "/"), oss.HTTPGet, 100)
```

**Comment by calfzhou** [comment]
这个问题是不考虑修复吗？目前还是会这样，SignUrl 得到的结果，把文件路径中的 `/` 都变成 `%2F` 了。用 `url.PathUnescape` 并不合适，它会把 url 最后的 Signature 末尾的 `%3D` 转换成 `=`。

**Comment by mtiller** [comment]
I agree with the above comment (at least what Google translated it to).  Why is `url.QueryEscape` being called in `buildURL` at all?  This **isnt'** a query string, this is a path component.  This is just wrong.  You might want to do Go's equivalent of Javascripts [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) (because that explicitly leaves `/` alone, as it should).

My fix for this is to first Sign the URL and _then_ run `url.PathUnescape` on the URL, _e.g.,_

```go
	// Ask Aliyun library to sign the URL
	aliurl, err := bucket.SignURL(file, "GET", 60*60)
	if err != nil {
		// notest
		return "", err
	}
        // Parse the resulting URL
	ur, err := url.Parse(aliurl)
	if err != nil {
		return "", err
	}
	// This bit fixes an unnecessary (and incorrect, IMHO) encoding performed by the
	// Aliyun Go SDK.
	epath, err := url.PathUnescape(ur.Path)
	if err != nil {
		return "", err
	}
        // Plug the correct path back into the URL
	ur.Path = epath
	ur.RawPath = epath
	return ur.String(), nil
```

But this shouldn't be necessary and it probably doesn't work for some problematic URLs (which I fortunately don't seem to have).
